app:
  port: :8080

log:
  level: debug #debug / info / warn / error / dpanic / panic / fatal
  filename: ./logs/dev.log
  maxSize: 10 #MB
  maxAge: 1 #days
  maxBackups: 7

mysql:
  dsn: root:admin123@tcp(localhost:3306)/go-gin-template?charset=utf8mb4&parseTime=true
