definitions:
  iomodel.LoginIM:
    properties:
      password:
        type: string
      phone_number:
        type: string
    type: object
  iomodel.LoginOM:
    properties:
      token:
        type: string
      uid:
        type: integer
    type: object
  iomodel.RegisterIM:
    properties:
      age:
        type: integer
      name:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
  response.Response-iomodel_LoginOM:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/iomodel.LoginOM'
      msg:
        type: string
    type: object
  response.Response-string:
    properties:
      code:
        type: integer
      data:
        type: string
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/session:
    post:
      consumes:
      - application/json
      description: 通过账户密码登录
      parameters:
      - description: login input model
        in: body
        name: LoginIM
        required: true
        schema:
          $ref: '#/definitions/iomodel.LoginIM'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response-iomodel_LoginOM'
      summary: 登录
      tags:
      - user
  /user/user:
    post:
      consumes:
      - application/json
      description: 输入账户密码用户信息注册
      parameters:
      - description: register input model
        in: body
        name: RegisterIM
        required: true
        schema:
          $ref: '#/definitions/iomodel.RegisterIM'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response-string'
      summary: 注册
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
