definitions:
  response.Response-int:
    properties:
      code:
        type: integer
      data:
        type: integer
      msg:
        type: string
    type: object
  user.LoginIM:
    properties:
      password:
        type: string
      phone_number:
        type: string
    type: object
  user.RegisterIM:
    properties:
      age:
        type: integer
      name:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/session:
    post:
      consumes:
      - application/json
      description: 通过账户密码登录
      parameters:
      - description: login input model
        in: body
        name: LoginIM
        required: true
        schema:
          $ref: '#/definitions/user.LoginIM'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response-int'
      summary: 登录
      tags:
      - user
  /user/user:
    post:
      consumes:
      - application/json
      description: 输入账户密码用户信息注册
      parameters:
      - description: register input model
        in: body
        name: RegisterIM
        required: true
        schema:
          $ref: '#/definitions/user.RegisterIM'
      produces:
      - application/json
      responses: {}
      summary: 注册
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
